### ISSUE TITLE
ansible-playbook error on clean install

### ISSUE THREAD

**Issue by jmslbam** [keichan34/wp-nginx-hhvm-mariadb#2]
Hi, just hanging this out here.
Just ran a clean install `vagrant up` and all went well untill I got this error

```
==> default: Running provisioner: ansible...
The executable 'ansible-playbook' Vagrant is trying to run was not
found in the PATH variable. This is an error. Please verify
this software is installed and on the path.
```

After excecuting an other `vagrant up` it does say it's already running. But nothing is provisioned.

---

Found this SA anwser : http://stackoverflow.com/questions/19388058/failover-provisioners-in-vagrant.
Tried to apply the fix `do_ansible =`ansible-playbook --version`rescue nil` but `vagrant up` just says it's already done. So I will dive into it some more.

Quite new to the whole Vagrant and Ansible thing so it might take some time. 
Will provide feedback when I know 

Thanks for the code btw.

Ciao,

Jaime

**Comment by jmslbam** [comment]
So I had to install Ansible locally :) yeah. Will add it to the Read Me.

**Comment by keichan34** [comment]
Ah, yeah. I'll add that to the readme -- sorry about that!

On May 3, 2014, at 8:30 AM, Jaime Martinez notifications@github.com wrote:

So I had to install Ansible locally :) yeah. Will add it to the Read Me.

—
Reply to this email directly or view it on
GitHubhttps://github.com/keichan34/wp-nginx-hhvm-mariadb/issues/2#issuecomment-42088967
.

**Comment by jmslbam** [comment]
I just opened a PR https://github.com/keichan34/wp-nginx-hhvm-mariadb/pull/3 which points to the installation section of the Ansible page.

And this machine is really really fast, amazing! Me likes

**Comment by keichan34** [comment]
Awesome, thanks! :smiley:
