### ISSUE TITLE
More WordPress Options

### ISSUE THREAD

**Issue by danadalis** [keichan34/wp-nginx-hhvm-mariadb#7]
Dont know if you seen this repository, https://github.com/GeekPress/WP-Quick-Install
maybe its something you can work with.

I use it to build wp installs, works like a charm.
Nice to see if you could get it to work with this stack.

**Comment by keichan34** [comment]
I haven't been using this for awhile, so you're free to implement a fork that uses wp-quick-install instead of whatever I'm using (I think I'm using wp-cli for most of it).
